name: release

on:
  push:
    tags:
      - "v*" # 只对以 'v' 开头的标签触发（例如 v1.0, v2.0）

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract tag name
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Extracted tag name: $TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ env.TAG_NAME }}
